apiVersion: v1
kind: Service
metadata:
  name: tracee-metrics
spec:
  internalTrafficPolicy: Cluster
  ports:
    - port: 3366
      name: metrics
      protocol: TCP
      targetPort: 3366
  selector:
    app.kubernetes.io/instance: tracee
    app.kubernetes.io/name: tracee
  type: ClusterIP