FROM bitnami/kubectl:latest as kubectl

FROM ubuntu:latest
# Do whatever you need to with the
# ubuntu-or-whatever-image:tag image, then:

COPY --from=kubectl /opt/bitnami/kubectl/bin/kubectl /usr/local/bin/
RUN  apt update
RUN  apt install -y jq
RUN mkdir -p /scripts
COPY /scripts /scripts
WORKDIR /scripts
RUN chmod +x /scripts/*.sh


