apiVersion: apps/v1
kind: Deployment
metadata:
  name: unsafe-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unsafe-test
  template:
    metadata:
      labels:
        app: unsafe-test

    spec:
      serviceAccountName: internal-kubectl
      containers:
        - name: tester
          image: madhuakula/hacker-container
          imagePullPolicy: Always
