apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "ssh-spawn-bash"
spec:
  kprobes:
    - call: "sys_execve"
      syscall: true
      args:
        - index: 0
          type: "string"
      selectors:
        - matchBinaries:
            - operator: "In"
              values:
                - "/usr/sbin/sshd"
          matchArgs:
            - index: 0
              operator: "Equal"
              values:
                - "/bin/sh"
