apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    meta.helm.sh/release-name: unguard
    meta.helm.sh/release-namespace: unguard
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: user-simulator
    app.kubernetes.io/part-of: unguard
  name: unguard-user-simulator
  namespace: unguard
  resourceVersion: "3081613"
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - env:
            - name: FRONTEND_ADDR
              value: unguard-envoy-proxy:8080/ui
            - name: SIMULATE_PRIVATE_RANGES
              value: "false"
            image: ghcr.io/dynatrace-oss/unguard/unguard-user-simulator:0.9.3
            imagePullPolicy: IfNotPresent
            name: unguard-user-simulator
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 10m
                memory: 256Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
  schedule: '*/3 * * * *'
  startingDeadlineSeconds: 180
  successfulJobsHistoryLimit: 3
  suspend: false
